### PR TITLE
Add a link to documentation in 'prep your release' reminder

### PR DESCRIPTION
**Pull request by girasquid**
Every time I get pinged to do this I have to go dig up the documentation again. This saves me a step, and probably also anyone else who has the same problem.

### CODE REVIEW

**Comment by girasquid** [comment]
Should it link to https://github.com/clio/themis/blob/master/dev-docs/deploying%20code.md#1-prepare instead?

**Comment by karina-clio** [comment]
I am not sure.  if they don't know how to prep they probably need that setup stuff that comes before?

**Comment by girasquid** [comment]
Yeah I'm torn - I've got that setup stuff done, but I also keep forgetting how to prep. I think I'll leave it as it is for now, still an improvement.

**Comment by girasquid** [comment]
This is no longer valid in the brave new world! Closing.

**Pull request closed without merging**
